# Generated by Django 6.0.3 on 2026-04-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_city_profile_latitude_profile_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Private — only used to calculate distance, never shown to others'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', help_text='Shown publicly as your general location', max_length=200),
        ),
    ]
