# Generated by Django 6.0.3 on 2026-04-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_address_alter_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_encrypted',
            field=models.TextField(blank=True, default='', help_text='AES-256-GCM encrypted address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='credit_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_preference',
            field=models.CharField(choices=[('bookswap_id', 'BookSwap ID (anonymous)'), ('real_name', 'Real Name')], default='bookswap_id', max_length=20),
        ),
    ]
