# Generated by Django 6.0.3 on 2026-04-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_address_encrypted_profile_credit_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
        migrations.AlterField(
            model_name='profile',
            name='credit_balance',
            field=models.IntegerField(default=3),
        ),
    ]
