# Generated by Django 6.0.3 on 2026-04-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_points_alter_profile_credit_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed_swaps_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified_shipper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
