# Generated by Django 6.0.3 on 2026-03-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_bookinstance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='book',
            name='popularity_rank',
            field=models.IntegerField(blank=True, help_text='Rank from Open Library trending (lower = more popular)', null=True),
        ),
    ]
