# Generated by Django 6.0.3 on 2026-03-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_book_cover_url_book_popularity_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Enter a brief description of the book'),
        ),
    ]
