# Generated by Django 6.0.3 on 2026-03-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_pointtransaction_swaprequest_shippingreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
