# Generated by Django 6.0.3 on 2026-04-01 14:03

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_book_credit_value_swaprequest_credits_earned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingreceipt',
            name='points_awarded',
        ),
        migrations.RemoveField(
            model_name='swaprequest',
            name='points_spent',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='popularity_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='condition',
            field=models.CharField(blank=True, choices=[('l', 'Like New'), ('v', 'Very Good'), ('g', 'Good'), ('a', 'Acceptable')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('s', 'Swapped')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='type',
            field=models.CharField(blank=True, choices=[('h', 'Hardcover'), ('p', 'Paperback')], default='m', max_length=1),
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PointTransaction',
        ),
    ]
