# Generated by Django 6.0.3 on 2026-04-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_swaprequest_arrived_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='book_photos/'),
        ),
    ]
