# Generated by Django 6.0.3 on 2026-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_bookinstance_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=20, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cached_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
